# 第二十天知识点总结：协方差与相关系数

## 1. 协方差 (Covariance)

### 1.1 定义
协方差用于衡量两个随机变量 **X** 和 **Y** 之间**线性相关**的方向和强度。

**总体协方差**：
$$
\operatorname{Cov}(X,Y) = E\big[(X - \mu_X)(Y - \mu_Y)\big]
$$

**样本协方差（常用）**：
$$
s_{XY} = \frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})
$$

> **注意**：分母为 $n-1$ 得到无偏估计；机器学习中做极大似然估计(MLE)时，也会使用分母 $n$。

### 1.2 直观理解
- 将数据点按 $(x_i - \bar{x})$ 和 $(y_i - \bar{y})$ 划分到四个象限。
- 多数点落在**一、三象限**（偏差同号）→ 协方差为正 → 正相关。
- 多数点落在**二、四象限**（偏差异号）→ 协方差为负 → 负相关。
- 点均匀分布在四个象限 → 协方差接近 0 → 无线性相关。

### 1.3 性质
- 对称性：
$$
\operatorname{Cov}(X,Y) = \operatorname{Cov}(Y,X)
$$

- 线性变换性质：
$$
\operatorname{Cov}(aX+b,\; cY+d) = a c \cdot \operatorname{Cov}(X,Y)
$$

- 方差是协方差的特例：
$$
\operatorname{Cov}(X,X) = \operatorname{Var}(X)
$$

- 若 $X$ 与 $Y$ 相互独立，则 $\operatorname{Cov}(X,Y)=0$；**反之不成立**（协方差为0仅代表无线性相关，仍可能存在非线性关系）。

### 1.4 局限性
1. **受量纲影响**：变量单位改变，协方差数值会随之变化，无法直接对比不同变量组的关联强弱。
2. 仅能度量**线性关系**，无法识别非线性相关（例如 $Y=X^2$ 这类非线性关系，协方差可能为 0）。

---

## 2. 相关系数 (Correlation Coefficient)

### 2.1 定义
皮尔逊相关系数（Pearson correlation coefficient）是**协方差的标准化形式**，消除了量纲影响。

**总体相关系数**：
$$
\rho_{XY} = \frac{\operatorname{Cov}(X,Y)}{\sigma_X \sigma_Y}
$$

**样本相关系数**：
$$
r_{XY} = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^{n}(x_i - \bar{x})^2}\sqrt{\sum_{i=1}^{n}(y_i - \bar{y})^2}}
$$

### 2.2 取值范围与解释
相关系数取值：$r \in [-1, 1]$
- $r = 1$：完全正线性相关，所有样本点落在一条递增直线上
- $r = -1$：完全负线性相关，所有样本点落在一条递减直线上
- $r = 0$：无线性相关关系（不排除非线性相关）

### 2.3 性质
- 无量纲，不受变量单位影响，可跨组比较相关性强弱。
- 满足对称性：$\rho_{XY} = \rho_{YX}$。
- 对**线性变换**保持不变。

### 2.4 与协方差的关系
由公式可相互推导：
$$
\rho = \frac{\operatorname{Cov}(X,Y)}{\sigma_X \sigma_Y}
$$

变形得协方差：
$$
\operatorname{Cov}(X,Y) = \rho \cdot \sigma_X \sigma_Y
$$

---

## 3. 代码实践要点（NumPy）

### 3.1 计算协方差矩阵 & 协方差
```python
import numpy as np

X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 4, 6, 8, 10])

# ddof=1：无偏样本协方差（分母 n-1，默认）
# ddof=0：总体协方差 / MLE 估计（分母 n）
cov_matrix = np.cov(X, Y, ddof=1)

# 提取 X 与 Y 的协方差
cov_xy = cov_matrix[0, 1]
print("协方差矩阵：\n", cov_matrix)
print("X 和 Y 的协方差：", cov_xy)


###  协方差和相关系数（皮尔逊相关系数）代码的常规使用和注意

1. np.cov(m,y=None,ddof=1,rowvar=True)

常规参数：m、y：输入两组一维数组（两个变量 X，Y）

ddof ：自由度参数，核心参数
    
    ddof=1（默认）：样本协方差，分母 n-1（无偏估计）

    ddof=0：总体协方差 / MLE ，分母 n

rowvar=True：每行代表一个变量（默认）

2. numpy.corrcoef(x, y=None, rowvar=True)：

作用 ：计算皮尔逊相关系数，结果范围[-1,1]

· 无 ddof 参数：相关系数会自动抵消分母，ddof 不印象结果



In [14]:
## 练习1：生成三组数据，分别计算协方差和相关系数，答应结果，并解释是正相关、负相关还是不相关

import numpy as np

# np.random.seed(42)
data1=np.random.randn(20)
data2=np.random.randn(20)
data3=np.random.randn(20)
x=np.vstack([data1,data2,data3])
# print(x)

# 计算协方差
cov_matrix=np.cov(x,ddof=0)
cov=cov_matrix[0,1]
print("协方差矩阵：\n",cov_matrix)
# print("三组数据的协方差为：",cov)

# 计算相关系数
cor_matrix=np.corrcoef(x,rowvar=True)
print("相关系数矩阵为：\n",cor_matrix)

# 解释
pairs=[(0,1,"data1,data2"),(0,2,"data1,data3"),(1,2,"data2,data3")]
for i,j,name in pairs:
    r=cor_matrix[i,j]
    if abs(r)<0.2:
        rel='几乎不相关'
    elif r>0:
        rel='正相关'
    else:
        rel='负相关'
    print(f"{name}:相关系数={r:.4f} -> {rel}")

协方差矩阵：
 [[ 0.87640865  0.220832   -0.07116892]
 [ 0.220832    0.30486269 -0.08055816]
 [-0.07116892 -0.08055816  0.59243903]]
相关系数矩阵为：
 [[ 1.          0.42722489 -0.09876776]
 [ 0.42722489  1.         -0.18955514]
 [-0.09876776 -0.18955514  1.        ]]
data1,data2:相关系数=0.4272 -> 正相关
data1,data3:相关系数=-0.0988 -> 几乎不相关
data2,data3:相关系数=-0.1896 -> 几乎不相关


In [15]:
## 练习2：生成两组高度相关的数据和两组看似相关但实际无关的数据，计算相关系数。

import numpy as np

np.random.seed(42)
x=np.random.randn(10)
noise=np.random.randn(len(x))
y_positive=2*x+noise
y_negative=-2*x+noise
Y=np.random.randn(len(x))
# rng=np.random.default_rng()
# m=rng.integers(5)
# n=rng.integers(5)
cor_xy_p=np.corrcoef(x,y_positive,rowvar=True)[0,1]
cor_xy_n=np.corrcoef(x,y_negative,rowvar=True)[0,1]
cor_xy=np.corrcoef(x,Y,rowvar=True)[0,1]

# |r|>=0.9(高度相关) 0.6<=|r|<=0.8(显著相关) |r|<0.2(几乎无线性相关)
print(f"正相关数据(y=2*x+noise): 相关系数={cor_xy_p:.4f} -> 高度正相关")
print(f"复相关数据(y=-2*x+noise): 相关系数={cor_xy_n:.4f} -> 高度负相关")
print(f"随机数据：相关系数={cor_xy:.4f} -> 数据没有明显关系")

正相关数据(y=2*x+noise): 相关系数=0.8759 -> 高度正相关
复相关数据(y=-2*x+noise): 相关系数=-0.8977 -> 高度负相关
随机数据：相关系数=-0.3167 -> 数据没有明显关系
