Numpy 梯度 np.gradient 最全总结
 
一、核心原理
 
无需函数解析式，仅依靠离散数组数值，通过有限差分法近似求导，得到数值梯度
 
二、差分计算规则
 
设元素间距为 h
 
1. 首尾边界点：单侧差分
首尾边界单侧差分：
$g_0=\frac{f_1-f_0}{h},\quad g_{last}=\frac{f_{last}-f_{last-1}}{h}$

中间点中心差分：
$g_i=\frac{f_{i+1}-f_{i-1}}{2h}$
3. 不传间距默认 h=1
 
三、一维数组求梯度
 
python
  
import numpy as np
arr = np.array([2,4,7,11,16])
grad = np.gradient(arr)
 
 
- 仅做左右方向差分
- 输出数组与原数组长度一致
 
四、二维数组求梯度（重点）
 
数组格式： (行数, 列数) 
 
轴方向死记口诀
 
-  axis=0 ：竖方向、跨行、按列计算
-  axis=1 ：横方向、跨列、按行计算
- 通用口诀：0竖1横
 
固定返回顺序
 
python
  
dy, dx = np.gradient(二维数组)
 
 
1. dy：对应 axis=0 ，竖直方向梯度 f/dy
2. dx：对应 axis=1 ，水平方向梯度 f/dx
 
自定义坐标间距
 
python
  
# 顺序：竖直方向间距 , 水平方向间距
dy, dx = np.gradient(数组, h_y, h_x)
 
 
五、高维数组拓展
 
python
  
# 三维数组
dz, dy, dx = np.gradient(三维数组)
 
 
严格按照维度顺序，依次输出三个方向梯度，计算逻辑不变
 
六、axis 通用所有Numpy函数规则
 
1.  axis=0 ：竖着运算，遍历整列，合并行
2.  axis=1 ：横着运算，遍历整行，合并列
 
七、数值梯度 vs 数学解析梯度
 
1. 数学梯度：依靠函数公式推导，结果为精确值
2. Numpy梯度：仅依靠离散数据计算，结果为近似值，步长越小精度越高
 
八、极简代码模板
 
python
  
# 一维
g1 = np.gradient(一维数组)

# 二维
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
dy, dx = np.gradient(data)


In [1]:
import numpy as np

# 只给一维数组，不用写 f(x) 的表达式
f = np.array([1, 3, 7, 13, 21])

# 直接求梯度
grad = np.gradient(f)
print("一维梯度：", grad)
# 二维数组，相当于一个 3x3 的函数值网格
f = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 沿两个方向求梯度：grad_y（列方向）、grad_x（行方向）
grad_y, grad_x = np.gradient(f)

print("沿 y 方向梯度：\n", grad_y)
print("沿 x 方向梯度：\n", grad_x)

一维梯度： [2. 3. 5. 7. 8.]
沿 y 方向梯度：
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
沿 x 方向梯度：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 梯度与方向导数

---

### 一、梯度（Gradient）

#### 1. 定义
设二元函数 $z = f(x,y)$ 在点 $(x,y)$ 处可微，则它的梯度是一个向量，定义为：
$$
\nabla f(x,y) = \left( \frac{\partial f}{\partial x},\ \frac{\partial f}{\partial y} \right)
$$

三元函数 $u = f(x,y,z)$ 的梯度为：
$$
\nabla f(x,y,z) = \left( \frac{\partial f}{\partial x},\ \frac{\partial f}{\partial y},\ \frac{\partial f}{\partial z} \right)
$$

#### 2. 核心性质
- 梯度的方向：函数**增长最快**的方向。
- 梯度的模长：函数在该方向上的**最大变化率**。
- 梯度与等值线（面）的关系：梯度方向**垂直于等值线/面**，指向函数值增大的一侧。

---

### 二、方向导数（Directional Derivative）

#### 1. 定义
设函数 $z = f(x,y)$ 在点 $(x,y)$ 处可微，沿单位方向向量 $\boldsymbol{e} = (\cos\alpha,\ \cos\beta)$ 的方向导数为：
$$
\frac{\partial f}{\partial l} = \lim_{t \to 0^+} \frac{f(x+t\cos\alpha,\ y+t\cos\beta) - f(x,y)}{t}
$$

它表示函数在该点沿 $\boldsymbol{e}$ 方向的变化率。

#### 2. 计算公式（可微函数）
方向导数等于梯度与方向向量的点积：
$$
\frac{\partial f}{\partial l} = \nabla f \cdot \boldsymbol{e} = \frac{\partial f}{\partial x}\cos\alpha + \frac{\partial f}{\partial y}\cos\beta
$$

三元函数的方向导数：
$$
\frac{\partial f}{\partial l} = \frac{\partial f}{\partial x}\cos\alpha + \frac{\partial f}{\partial y}\cos\beta + \frac{\partial f}{\partial z}\cos\gamma
$$
其中 $\cos\alpha,\cos\beta,\cos\gamma$ 是方向向量的方向余弦。

#### 3. 几何意义
- 方向导数 $>0$：函数沿该方向**上升**。
- 方向导数 $<0$：函数沿该方向**下降**。
- 方向导数 $=0$：函数沿该方向**不变**（沿等值线切线方向）。

---

### 三、梯度与方向导数的关系

由方向导数公式：
$$
\frac{\partial f}{\partial l} = |\nabla f| \cos\theta
$$
其中 $\theta$ 是梯度 $\nabla f$ 与方向向量 $\boldsymbol{e}$ 的夹角。

由此可得：
1. 当 $\theta=0$（方向与梯度同向）：
   $\cos\theta=1$，方向导数取最大值 $|\nabla f|$，函数增长最快。
2. 当 $\theta=\pi$（方向与梯度反向）：
   $\cos\theta=-1$，方向导数取最小值 $-|\nabla f|$，函数下降最快。
3. 当 $\theta=\frac{\pi}{2}$（方向与梯度垂直）：
   $\cos\theta=0$，方向导数为 $0$，函数在该方向不变。

---

### 四、关键对比表

| 概念 | 梯度 | 方向导数 |
|------|------|----------|
| 性质 | 向量 | 标量 |
| 描述 | 函数增长最快的方向与速率 | 某一特定方向上的变化率 |
| 与方向的关系 | 方向固定（指向增长最快处） | 随方向改变而改变 |
| 公式 | $\nabla f = \left( \frac{\partial f}{\partial x},\frac{\partial f}{\partial y} \right)$ | $\frac{\partial f}{\partial l} = \nabla f \cdot \boldsymbol{e}$ |