In [ ]:
import numpy as np
a=np.array([2,4,5,9,3,7,8])
# print(a)
# print(a[0])
# print(a[2])
# a[3]=1
# print(a)
# print(a[:2])
# b=a[3:]
# print(b)
# print(a)
# b[0]=10
# print(b)
# print(a)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c[0,2])
print(c.shape)
print(a.ndim)
import math
f=c.size
print(f)
g=math.prod(c.shape)
print(f==g)
print(c.dtype)

一、数组属性
1. a.ndim 数组的维度数包含在ndim属性中
2. a.shape 是指该数组的行列数
3. a.size 数组中的固定、总元素数包含在size属性中
4. math.prod(可迭代对象) 把可迭代对象里的所有数相乘，返回乘积
5. a.dtype 数组通常是"同质的",这意味着它们只包含一种"数据类型"的元素。数据类型记录在dtype属性中

二、如何创建基本数组
1. np.zeros() 创建充满 0 的数组
2. np.ones() 创建充满 1 的数组
3. np.empty() 创建一个初始内容随机的数组，具体内容取决于内存状态
4. np.arange() 创建一个包含元素范围的数组（和 range() 的用法一样）可以指定第一个数、最后一个数和步长
5. np.linspace() 创建一个指定区间内线性间隔的数组
6. 虽然默认数据类型是浮点数 (np.float64) ，但可以使用 dtype 关键字明确指定所需要的数据类型
Q : 之前的输出数组之间都有“ . ” 也是因为默认为了浮点数

In [ ]:
import numpy as np
print(np.zeros(2))
print(np.ones(3))
print(np.empty(4))
print(np.arange(2,10,3))
print(np.linspace(0,9,num=4))
x=np.ones(3,dtype=np.int64)
print(x)

三、添加、删除和排序元素
1. np.sort() 可以轻松地对数组进行排序，可以在调用函数时指定轴、种类和顺序
2. np.concatenate() 把两个数组连接起来


In [ ]:
import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
o=np.sort(arr)
print(o)
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.concatenate((a,b)))
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8]])
z=np.concatenate((x,y),axis=0)
print(z)

四、如何知道数组的形状和大小
1. ndarray.ndim 告诉数组的轴数和维度
2. ndarray.size 告诉数组的总元素数
3. ndarray.shape 显示一整个元素组，指示数组每个维度上存储的元素数量

In [ ]:
import numpy as np
array_example=np.array([[[0,1,2],[4,5,6]],
                        [[4,3,2],[9,8,7]],
                        [[7,6,5],[2,3,4]]])
arr=np.array([1,2,3,4])
print(arr.ndim)
print(array_example)
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)


五、重塑数组
1. arr.reshape() 可以为数组提供新形状，而不会改变数据

In [ ]:
import numpy as np
a=np.arange(6)
print(a)
print(a.ndim)
b=a.reshape(3,2)
print(b)
print(b.ndim)

六、如何将一维数组转换为二维数组（如何为数组添加新轴）
1. np.newaxis 增加现有数组的维度
2. np.expand_dims 在指定位置扩展数组，插入新轴

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a.shape)
row_vector=a[np.newaxis,:]
print(row_vector)
print(row_vector.shape)
col_vector=a[:,np.newaxis]
print(col_vector)
print(col_vector.shape)
b=np.expand_dims(a,axis=1)
print(b)
print(b.shape)
c=np.expand_dims(a,axis=0)
print(c)
print(c.shape)

七、索引和切片
1. & 表示 and 的意思， | 用来判断是否正确返回布尔值的
2. np.nonzero() 从数组中选择元素或索引,返回的是行和列
3. zip()可以把数组打包

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# print(a[a<5])
# five_up=(a>=5)
# print(a[five_up])
# divisible_by_2=a[a%2==0]
# print(divisible_by_2)
# c=a[(a>2)&(a<11)]
# print(c)
# five_up_2=(a>5)|(a==5)
# print(five_up_2)
f=np.nonzero(a<5)
print(f)
# list_of_coordnates=list(zip(f[0],f[1]))
# for coord in list_of_coordnates:
#     print(coord)
there=np.nonzero(a<5)
print(there)

八、如何从现有数据创建数组
1. 可以通过指定要切片数组的位置，随时从数组的一部分创建新数组
2. np.stack() 将数组垂直堆叠，np.hstack() 将数组水平堆叠
3. np.hsplit(arr,n)=np.split(arr,n,axis=1) 将一个数组分割成几个更小的数组，可以指定要返回的等形数组的数量，或者在哪些列之后进行分割(水平切割，按列来) np.vsplit(arr,n)=np.split(arr,n,axis=0) 垂直切割，按行来切
4. axis=0：行方向(相当于y轴)，作用是对列 ，axis=1：列反向（相当于x轴），作用是对行
5. arr.copy() 将创建数组及其数据的完整副本



In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
# part_1
arr1=a[3:8]
print(arr1)
#part_2
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,4]])
b=np.vstack((a1,a2))
print(b)
c=np.hstack((a1,a2))
print(c)
#part_3
x=np.arange(1,25).reshape(2,12)
print(x)
y=np.hsplit(x,3)
print(y)
z=np.hsplit(x,(3,4))
print(z)
t=np.vsplit(x,1)
print(t)
#part_5
w=x.copy()


九、基本数组运算
1. 在使用数组加法、减法、乘法和除法时必须保证两个数组的行列数是相同的，不然就会报错
2. arr.sum() 可以得出数组中元素的总和
3. 广播是一种允许numpy对不同形状的数组执行操作的机制，数组的维度必须兼容（如：当两个数组的维度相同或其中一个为1时）
如果维度不兼容，会得到 ValueError


In [ ]:
import numpy as np
#part_1
data=np.array([1,2,3])
ones=np.ones(3,dtype=int)
print(data+ones)
print(data-ones)
print(data*data)
#part_2
b=np.array([[1,1],[2,3]])
c=b.sum(axis=0)
d=b.sum(axis=1)
print(c,d)

十、更多有用的数组操作
1. 除了min、max、sum、，还可以通过mean来获取平均值，prod老获取将元素相乘的结果，std获取标准差
2. 可以指定 axis=0 或 axis=1 来找每行、列中最小的值
3. arr[n:n] numpy切片只切行
4. np.ones(块数,行数,列数)
5. arr=np.random.default_rng() 再 arr.random() 是最简单的方式去产生随机数。用于生成随机数的 random.Generator 类


In [ ]:
import numpy as np
x=np.array([[1,4],[2,9],[3,5]])
# print(x)
y=x.min(axis=0)
z=x.min(axis=1)
print(y)
print(z)
# print(x[1:3])#只切列1和列2
ones_row=np.array([[1,1]])
print(x.ndim,ones_row.ndim)
print(x+ones_row)
a=np.ones((4,3,2))
print(a)
# rng=np.random.default_rng()
# t=rng.random((3,2))
# print(t)


十一、 生成随机数
1. 使用 Generator.integers,可以生成从低（再NumPy中，这包括在内）到高（不包括在内）的随机整数。可以设置 endpiont=True
来使高位数字也可以包含在内
2. 使用老式的 np.random.random() 和 np.rondom.rondint() 也可以随机生成数组（最好还是用新版，旧版快要被淘汰了）

In [ ]:
import numpy as np
rng=np.random.default_rng()
t=rng.integers(5,size=(2,4),endpoint=True)
print(t)

十二、如何获取唯一项和计数
1. np.unique() 找到数组中的唯一元素，没有完全相同的行或列时，就会自动按顺序排序
2. 要获取Numpy数组中唯一值的索引（唯一值在数组中的第一个索引位置的数组），只需将 return_index 参数和数组一起传递给 np.unique()
3. 将 return_counts 参数和你的数组一起传递给 np.unique() ,以获取NumPy数组中唯一值的频率

In [ ]:
import numpy as np
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values=np.unique(a)
print(unique_values)
unique_values,indicess_list=np.unique(a,return_index=True)
print(indicess_list)
unique_values,occurrence_count=np.unique(a,return_counts=True)
print(occurrence_count)
a_2d = np.array([[1, 2, 3, 1], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_rows=np.unique(a_2d,axis=1)
print(unique_rows)
unique_rows,indices,occurrence=np.unique(a_2d,axis=0,return_counts=True,return_index=True)
print(indices)
print(occurrence)#把每一列看成一个整体就看得懂了

十三、转置和重塑矩阵
1. arr.reshape() 输入特定的形状
2. arr.transpose()=arr.T  根据指定值反转或更改数组的轴
3. axis（单数）：指单个维度。 axes（复数）指多个维度的集合/顺序

In [ ]:
import numpy as np
arr=np.arange(6).reshape((2,3))
print(arr)
b=arr.transpose()
print(b)
arr_3d=np.ones((2,3,4))
print("原形状：",arr_3d.shape)
arr_t1=np.transpose(arr_3d)
print("默认转置之后的形状：",arr_t1.shape)
arr_t2=np.transpose(arr_3d,axes=(1,0,2))
print("指定axes=(1,0,2)后形状：",arr_t2.shape)

十四、如何反转数组
1. Numpy 的 np.flip() 函数允许沿某个轴翻转或反转数组的内容，在使用np.flip() 时，请指定想反转的数组和轴，如果不指定轴，NumPy 会反转输入数组的所有轴上的内容
2. 反转行 arr[n]=np.flip(arr[n])(索引为n的行) 
3. 反转列 arr[:,n]=np.flip(arr[:,n]) （反转索引为n的列）

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr=np.flip(arr)
print("反转一维数组：",reversed_arr)
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("反转二维数组：",np.flip(arr_2d))
reversed_arr_rows=np.flip(arr_2d,axis=0)
print("反转行：",reversed_arr_rows)
reversed_arr_columns=np.flip(arr_2d,axis=1)
print("反转列：",reversed_arr_columns)
arr_2d[1]=np.flip(arr_2d[1])
print("只反转某一行的内容：",arr_2d)
arr_2d[:,1] = np.flip(arr_2d[:,1])
print("同时反转第二列的内容：",arr_2d)


十五、重塑和展平多维数组
1. 展平数组有两种流行的办法： arr.flatten() 和arr.ravel() 。两者之间的区别在于，使用 arr.ravel() 创建的新数组实际上是对父数组的引用（即，“视图”），这意味着对新数组的任何更改都会影响父数组。由于 ravel 不需要创建副本，因此它的内存效率很高
2. 使用 arr.flatten() 时，对数组的更改不会改变父数组


In [ ]:
import numpy as np
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x.flatten())
a1=x.flatten()
a1[0]=99
print(x)
a2=x.ravel()
a2[0]=98
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


十六、如何访问文档字符串以获取更多信息
1. python 有一个内置的 help() 函数，可以帮助访问这些信息，帮助快速找到这些信息